config:
  target: "http://localhost:3000"
  phases:
    - duration: 60
      arrivalRate: 5
      name: Warm up
    - duration: 120
      arrivalRate: 5
      rampTo: 50
      name: Ramp up load
    - duration: 600
      arrivalRate: 50
      name: Sustained load
# payload:
#   path: "./product.csv"
#   fields:
#     - "page"
#     - "count"
scenarios:
  - name: "Load products"
    flow:
      - get:
          url: "/products"
#           json:
#             page: "{{ page }}"
#             count: "{{ count }}"